export const types = {
    ADD_TASK: "ADD_TASK",
    REMOVE_TASK: "REMOVE_TASK",
    UPDATE_TASK: "UPDATE_TASK",
    TOGGLE_TASK: "TOGGLE_TASK",
    ADD_CATEGORY: "ADD_CATEGORY",
    REMOVE_CATEGORY: "REMOVE_CATEGORY",
};
